name: Python Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (if any)
      run: |
        pip install -r requirements.txt || true  # ignore if no requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover
