name: Python Test

on: [push]

jobs:
  test:
    runs-on: self-hosted  # Use self-hosted unless your runner is named differently

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (if any)
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping dependency installation."
        fi

    - name: Run unit tests
      run: |
        python -m unittest discover
